env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - mod_timestamp: "{{ .CommitTimestamp }}"
    main: ./cmd/unityweb/main.go
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X "main.version={{ .RawVersion }}" -X "main.prerelease={{ if .IsSnapshot }}snapshot.{{ .ShortCommit }}{{ else }}{{ .Prerelease }}{{ end }}"'
    targets:
      - linux_386
      - linux_amd64
      - linux_arm
      - windows_386
      - windows_amd64
      - darwin_amd64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm
      - openbsd_386
      - openbsd_amd64

archives:
  - format: binary
    name_template: "unityweb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "unityweb_{{ .Version }}_SHA256SUM"
  algorithm: sha256

changelog:
  skip: true
